name: Multi-env deployment tracker

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name'
        type: string
        required: true

permissions:
  contents: read

jobs:

  deployment-tracker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Get DynamoDB Item
        id: tracker
        uses: mooyoul/dynamodb-actions@05013884a41c0972f87c4526da71939b36b86da1 # v1.2.3
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DYNAMODB_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DYNAMODB_AWS_SECRET_ACCESS_KEY }}
        with:
          operation: get
          region: ${{ secrets.AWS_REGION }}
          table: deployment-tracking
          key: |
            { repository: "${{ inputs.repository }}" }
            
      - name: Print item
        run: |
          echo '${{ steps.tracker.outputs.item }}'
     
