name: "Terraform provisioning for secrets manager"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true

jobs:

  terraform:
    permissions:
      id-token: write  # need this for OIDC
      contents: read
    uses: wenqiglantz/reusable-workflows-modules/.github/workflows/terraform.yml@main
    with:
      # need to specify working-directory as that's where the terraform files live in the source code
      working-directory: ./terraform/secrets-manager
    secrets: inherit
